name: Deploy to GitHub Pages

on:
  push:
    branches: ['master']
    paths:
      - 'website/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:
  workflow_run:
    workflows: ["Lint Markdown"]
    types:
      - completed
    branches: ['master']

permissions:
  contents: write
  actions: read

concurrency:
  group: 'gh-pages-deploy'
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build and Deploy Site
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: website
        run: npm install --no-package-lock

      - name: Build site
        working-directory: website
        run: npm run build

      - name: Verify build output
        run: |
          if [ ! -d "website/dist" ]; then
            echo "❌ Build failed - dist directory not found"
            exit 1
          fi
          echo "✅ Build successful"
          echo "Generated files:"
          ls -la website/dist/
          echo ""
          echo "Site structure:"
          find website/dist -type f | head -20

      - name: Deploy to web branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/dist
          publish_branch: web
          force_orphan: true

      - name: Output deployment info
        run: |
          echo "🚀 Site deployed successfully to web branch!"
          echo "🔗 GitHub Pages URL: https://${{ github.repository_owner }}.github.io/Eidolon_Lore/"
          echo "⚙️  Make sure GitHub Pages is configured to serve from web branch in repository settings"
